name: branch-1 workflow
on: 
   push:
     branches:
       - "branch-1"
jobs:
  my-first-job:
    name: My first jobs
    runs-on: ubuntu-latest
    steps:
      - name: say Hi
        run: |
          echo "Welcome to Github Actions"
          echo "This will only run on branch-1"
      - name: checking out code
        uses: actions/checkout@v3
      - name: list files
        run: |
          chmod +x ./script.sh && ls -lah 
      - name: run the script
        run: ./script.sh
      - name: output something
        run: |
          echo "Helloooooo" > file1.txt
          echo 'We are running on: ${{ runner.os }}'
      - name: upload the file
        uses: actions/upload-artifact@v2
        with:
          name: file-upload-1
          path: ./file1.txt

  my-second-job:
    name: My second jobs
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - name: download the file
        uses: actions/download-artifact@v2
        with:
          name: file-upload-1
      - name: view file
        run: |
          cat ./file1.txt


